### ISSUE TITLE
System.ArgumentNullException when running populate command

### ISSUE THREAD

**Issue by leaffan** [rezanid/novodocx#12]
Hejhej,
I was about to give novodocx a try but I'm unfortunately unable to get it running. A very simple execution to fill the included document ends with the following message:

`
$ ndocx.exe populate SimpleTemplate.docx

Unhandled exception: System.ArgumentNullException: Value cannot be null. (Parameter 'path')
   at System.IO.File.ReadAllText(String )
   at Novo.Docx.Cli.PopulateCommand.Run(ParseResult parseResult) in C:\Users\Reza\GitHub\novodocx\src\CLI\ndocx\commands\ndocx-populate\PopulateCommand.cs:line 32
   at Novo.Docx.Cli.ParseResultCommandHandler.InvokeAsync(InvocationContext context) in C:\Users\Reza\GitHub\novodocx\src\CLI\ndocx\commands\ParseResultCommandHandler.cs:line 20
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__23_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseExceptionHandler>b__0>d.MoveNext()
`

Do you have any idea what I could have done wrong here?

Thank you in advance for your efforts.

**Comment by rezanid** [comment]
Sorry to reply this late, could you tell me if you were testing it on mac / Windows?

**Comment by rezanid** [comment]
At this point I have a few guesses, but soon I will be making some minor cleanup and upgrades. While at it I will certainly look into this too.
